apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: riker-ingress
  namespace: team-riker
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
{{ if .Values.spec.ingress.host }}
  - host: guestbook-ui.{{ .Values.spec.ingress.host }}
{{ else }}
  - host:  
{{ end }}  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook-ui
            port: 
              number: 80
        
        