spec:
  destination:
    server: https://kubernetes.default.svc
# All helm parameters are sent by IaC code (Terraform or CDK)      
  apps:
    ecsdemoFrontend:
      repoURL: https://github.com/aws-containers/ecsdemo-frontend.git      
      targetRevision: main
      path: kubernetes/helm/ecsdemo-frontend
    ecsdemoNodejs:
      repoURL: https://github.com/aws-containers/ecsdemo-nodejs.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-nodejs
    ecsdemoCrystal:
      repoURL: https://github.com/aws-containers/ecsdemo-crystal.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-crystal