apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecsdemo-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ecsdemo-frontend
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.ecsdemoFrontend.repoURL }}
    targetRevision: {{ .Values.spec.apps.ecsdemoFrontend.targetRevision }}
    path: {{ .Values.spec.apps.ecsdemoFrontend.path }}
    helm:
      parameters:
      - name: ingress.enabled
        value: "true"
      - name: ingress.className
        value: "alb"
      # - name: ingress.annotations.'alb.ingress.kubernetes.io/target-type'
      #   value: "ip"

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
