apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecsdemo-nodejs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ecsdemo-nodejs
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.ecsdemoNodejs.repoURL }}
    targetRevision: {{ .Values.spec.apps.ecsdemoNodejs.targetRevision }}
    path: {{ .Values.spec.apps.ecsdemoNodejs.path }}
    helm:
      parameters:
      - name: replicaCount
        value: "3"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false # https://github.com/argoproj/argo-cd/issues/7799
