spec:
  destination:
    server: https://kubernetes.default.svc
# All helm parameters are sent by IaC code (Terraform or CDK)  
  source:
    repoURL: https://github.com/dexter-cc/eks-blueprints-workloads
    targetRevision: main
  # env: dev
  # clusterName:
  # blueprint: 'cdk/terraform'
  # karpenterInstanceProfile:
  # ingress:
  #   type: 'nginx/alb'
  #   host:
  ingress:
    host: dev.example.com