apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: burnham-ingress
  namespace: team-burnham
  labels:
    app: burnham-ingress-{{ .Values.spec.env }}
  annotations:
    alb.ingress.kubernetes.io/group.name: burnham
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: 'ip'
{{ if .Values.spec.ingress.host }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
{{ else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
{{ end }}
{{ if eq .Values.spec.ingress.host "cdk" }}      
    alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
{{ else }}
    alb.ingress.kubernetes.io/backend-protocol: 'HTTPS'
{{ end }} 
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=Burnham
spec:
  rules:
{{ if .Values.spec.ingress.host }}  
  - host: burnham.{{ .Values.spec.ingress.host }}  
{{ else }}  
  - host: 
{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eks-example
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eks-example
  labels:
    app: burnham-ingress-{{ .Values.spec.env }}  
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: eks-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-example
  labels:
    app: burnham-deployment-{{ .Values.spec.env }}
spec:
  #replicas: {{ int .Values.spec.replicas }}
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: eks-example
  template:
    metadata:
      labels:
        app: eks-example
        seb: test
    spec:
      containers:
        - name: eks-example
          image: public.ecr.aws/seb-demo/eks-example:a213b841
          ports:
            - containerPort: 80
      # nodeSelector:
      #   team: burnham
      #   type: karpenter
      # tolerations:
      #   - key: 'burnham'
      #     operator: 'Exists'
      #     effect: 'NoSchedule'
