apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: burnham
spec:
  requirements:
    # - key: 'node.kubernetes.io/instance-type'
    #   operator: In
    #   values: ['m5.xlarge', 'm5a.xlarge', 'm5ad.xlarge', 'm5d.xlarge', 't2.xlarge', 't3.xlarge', 't3a.xlarge']
    - key: 'kubernetes.io/arch'
      operator: In
      values: ['amd64']
    - key: karpenter.sh/capacity-type
      operator: In
      values: ['on-demand', 'spot']
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    kind: AWS
    instanceProfile: {{ .Values.spec.karpenterInstanceProfile }}
    securityGroupSelector:
      kubernetes.io/cluster/{{ .Values.clusterName }}: '*'
      #aws:eks:cluster-name: '{{ .Values.clusterName }}'
    subnetSelector:
      kubernetes.io/cluster/{{ .Values.clusterName }}: '*'
      #aws:cloudformation:stack-name: '{{ .Values.clusterName }}'
    tags:
      karpenter.sh/cluster_name: {{ .Values.clusterName }}
      karpenter.sh/provisioner: burnham
  ttlSecondsAfterEmpty: 0
  limits:
    resources:
      cpu: '200'
  labels:
    billing-team: burnham
    team: burnham
    type: karpenter
  taints:
    - key: burnham
      value: 'true'
      effect: NoSchedule
